ctic_bridge_sylius_bundle_shop_api_content_show:
    #path: /content/{slug}
    path: /content
    methods: [GET]
    defaults:
        _controller: ctic_bridge_sylius_bundle.shop_api.controller.content.show
    #requirements:
    #    slug: .+
