ctic_bridge_sylius_bundle_admin:
    resource: "@CTICBridgeSyliusBundle/Resources/config/routing/admin.yml"
    prefix: /admin

ctic_bridge_sylius_bundle_shop:
    resource: "@CTICBridgeSyliusBundle/Resources/config/routing/shop.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
