imports:
    - { resource: "@CTICBridgeSyliusBundle/Resources/config/services/form.yml" }
    - { resource: "@CTICBridgeSyliusBundle/Resources/config/services/factory.yml" }

services:
    ctic.bridge.sylius.eventlistener.themerequest:
        class: CTIC\Bridge\SyliusBundle\EventListener\ThemeRequestEventListener
        arguments: ['@sylius.repository.theme', '@sylius.theme.context.settable']
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    sylius.sitemap_provider.taxon:
        class: CTIC\Bridge\SyliusBundle\Provider\TaxonUrlProvider
        arguments: ['@sylius.repository.taxon', '@router', '@sylius.sitemap_url_factory', '@sylius.context.locale', '%sylius.sitemap_exclude_taxon_root%']
        tags:
          - { name: sylius.sitemap_provider }

# add admin options to menu
    ctic_bridge_sylius_bundle.menu.content_management:
        class: CTIC\Bridge\SyliusBundle\Menu\BrandingMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

# add branding repository as service
    ctic_bridge_sylius_bundle.branding.custom_repository:
        class: CTIC\Bridge\SyliusBundle\Repository\BrandingRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CTIC\Bridge\SyliusBundle\Entity\Branding

    ctic_bridge_sylius_bundle.context.channel_request_query_based:
        class: CTIC\Bridge\SyliusBundle\Context\RequestQueryChannelContext
        arguments:
            - '@sylius.repository.channel'
            - '@request_stack'
        tags:
            - { name: sylius.context.channel, priority: 100 }

# controller to configuration shop-api
    ctic_bridge_sylius_bundle.shop_api.controller.configuration.show:
        class: CTIC\Bridge\SyliusBundle\Controller\ShopApi\ShowConfigurationAction
        arguments:
            - '@ctic_bridge_sylius_bundle.branding.custom_repository'
            - '@sylius.repository.channel'
            - '@fos_rest.view_handler'
            - '@sylius.context.channel'
        tags:
            - { name: controller.service_arguments }

# controller to configuration shop-api
    ctic_bridge_sylius_bundle.shop_api.controller.content.show:
        class: CTIC\Bridge\SyliusBundle\Controller\ShopApi\ShowContentAction
        arguments:
            - '@sylius.repository.taxon'
            - '@sylius.shop_api_plugin.provider.current_user_provider'
            - '@sylius.shop_api_plugin.view_repository.product_catalog_view_repository'
            - '@sylius.repository.channel'
            - '@sylius.repository.customer'
            - '@fos_rest.view_handler'
            - '@sylius.context.channel'
            - '@sylius.shop_api_plugin.factory.taxon_details_view_factory'
            - '@sylius.shop_api_plugin.view_repository.placed_order_view_repository'
            - '@sylius.shop_api_plugin.http.request_based_locale_provider'
        tags:
            - { name: controller.service_arguments }

# Replace product repositories to shop api
    sylius.shop_api_plugin.view_repository.product_details_view_repository:
        class: CTIC\Bridge\SyliusBundle\ViewRepository\Product\ProductDetailsViewRepository
        arguments:
            - '@sylius.repository.channel'
            - '@sylius.repository.product'
            - '@sylius.shop_api_plugin.factory.detailed_product_view_factory'
            - '@sylius.shop_api_plugin.provider.supported_locale_provider'

    sylius.shop_api_plugin.view_repository.product_catalog_view_repository:
        class: CTIC\Bridge\SyliusBundle\ViewRepository\Product\ProductCatalogViewRepository
        arguments:
            - '@sylius.repository.channel'
            - '@sylius.repository.product'
            - '@sylius.repository.taxon'
            - '@sylius.shop_api_plugin.factory.list_product_view_factory'
            - '@sylius.shop_api_plugin.factory.page_view_factory'
            - '@sylius.shop_api_plugin.provider.supported_locale_provider'

    sylius.shop_api_plugin.view_repository.product_latest_view_repository:
        class: CTIC\Bridge\SyliusBundle\ViewRepository\Product\ProductLatestViewRepository
        arguments:
            - '@sylius.repository.channel'
            - '@sylius.repository.product'
            - '@sylius.shop_api_plugin.factory.list_product_view_factory'
            - '@sylius.shop_api_plugin.provider.supported_locale_provider'
