imports:
    - { resource: "@CTICBridgeSyliusBundle/Resources/config/services/form.yml" }

services:
    ctic.bridge.sylius.eventlistener.themerequest:
        class: CTIC\Bridge\SyliusBundle\EventListener\ThemeRequestEventListener
        arguments: ['@sylius.repository.theme', '@sylius.theme.context.settable']
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    sylius.sitemap_provider.taxon:
        class: CTIC\Bridge\SyliusBundle\Provider\TaxonUrlProvider
        arguments: ['@sylius.repository.taxon', '@router', '@sylius.sitemap_url_factory', '@sylius.context.locale', '%sylius.sitemap_exclude_taxon_root%']
        tags:
          - { name: sylius.sitemap_provider }

# add admin options to menu
    ctic_bridge_sylius_bundle.menu.content_management:
        class: CTIC\Bridge\SyliusBundle\Menu\BrandingMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    ctic_bridge_sylius_bundle.context.channel_request_query_based:
        class: CTIC\Bridge\SyliusBundle\Context\RequestQueryChannelContext
        arguments:
            - '@sylius.repository.channel'
            - '@request_stack'
        tags:
            - { name: sylius.context.channel, priority: 100 }
