CTIC\Bridge\BitbagCMSPlugin\Entity\Landing:
    type: mappedSuperclass
    table: ctic_cms_landing
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        elements:
            targetEntity: LandingElement
            mappedBy: landing
            cascade: ["persist", "remove"]