sylius_grid:
    grids:
        ctic_bridge_bitbag_cms_plugin_admin_landing:
            driver:
                name: doctrine/orm
                options:
                    class: "%ctic_bridge_bitbag_cms_plugin.model.landing.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                id: asc
            limits: [10, 25, 50]
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [id, name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
