services:
    ctic.sylius.importer.product_json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - "@sylius.manager.product"
            - "@ctic.sylius.processor.product"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: product, format: json }

#    ctic.sylius.importer.product_csv:
#        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
#        arguments:
#            - "@sylius.factory.csv_reader"
#            - "@sylius.manager.product"
#            - "@ctic.sylius.processor.product"
#            - "@sylius.importer.result"
#            - "%sylius.importer.batch_size%"
#            - "%sylius.importer.fail_on_incomplete%"
#            - "%sylius.importer.stop_on_failure%"
#        tags:
#            - { name: sylius.importer, type: product, format: csv }

    ctic.sylius.processor.product:
        class: CTIC\Bridge\FOSImportExportPlugin\Processor\ProductProcessor
        arguments:
            - "%kernel.project_dir%"
            - "@sylius.repository.channel"
            - "@sylius.factory.channel_pricing"
            - "@sylius.factory.product"
            - "@sylius.repository.product"
            - "@sylius.factory.taxon"
            - "@sylius.repository.taxon"
            - "@sylius.manager.taxon"
            - "@sylius.factory.product_taxon"
            - "@sylius.repository.product_taxon"
            - "@sylius.factory.product_attribute"
            - "@sylius.factory.product_attribute_value"
            - "@sylius.repository.product_attribute_value"
            - "@sylius.repository.product_attribute"
            - "@sylius.repository.product_option"
            - "@sylius.factory.product_option"
            - "@sylius.repository.product_option_value"
            - "@sylius.factory.product_option_value"
            - "@sylius.factory.product_variant"
            - "@sylius.repository.product_variant"
            - "@sylius.repository.tax_category"
            - "@property_accessor"
            - "@sylius.importer.metadata_validator"
            - "@sylius.image_uploader"
            - ["foto", "descripcion", "referencia", "pvp", "descripcio_familia", "fabricant", "disponible", "iva", "color"]
